### PR TITLE
Update demo adding 2 example widgets

### PR DESCRIPTION
**Pull request by stuartdd2**
I have added two widgets as examples and updated the examples application.

I have integrated the widgets to the examples application, providing icons and a Show method to display the two widgets.

These are intended to be full examples of creating fyne widgets from scratch.

The first widget contains a Renderer and an Animator. The second uses a Renderer and a time.Ticker.

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
Thanks for opening this. However, I still think the clock would be a useful contribution to fyne-x for anyone that would want to show a clock in their application. Especially since we already have a clock demo here among the examples. I’m also not entirely sure about having a new “widget” tab here. It’s a little bit vague given that a lot of other components in the application are just that, widgets.

Don’t get me wrong here, I appreciate it a lot that you want to contribute your code to help others. It is the moral of open source and I think it is very important. Thanks!

**Comment by stuartdd2** [comment]
My rational for this stems from my own experience with "Writing a Custom Widget". The fyne tutorials built a base but not enough to actually build a custom widget (with my limited experience). So I searched the internet for a concrete example. I did not find anything useful. 

I also did not find any in the examples presented in fyne/examples. I could not find any complete examples that for example implemented CreateRenderer(). 

I now see that if I looked much deeper I would see bug.go and a widget that extended a button. But no obvious widgets in the code that gives 'examples'. I see the vendor lib has some but these do not present as example code. I am not even sure at the moment what 'vendor' means in this context so I did not look!

Please don't get me wrong here, there are lots of very good examples of composing canvas objects and returning them but I wanted to understand and write my own "Custom Widget".

In the end, with Andy Williams considerable help and lots of good discussion, I wrote my first animated custom widget and then the clock widget.

I simply want to present these as 'good', 'working' examples of "Writing a Custom Widget".

I am more than happy to discuss tabs and icons and context and such. I am more than happy to add the clock widget to fyne-x. I just think the more examples the better.

Regards

Stuart

**Comment by Jacalz** [comment]
In that case, wouldn’t it then be better to write a tutorial on https://developer.fyne.io/? I think it’s the best way to fix the lack of good documentation about writing custom widgets. Adding more examples is not bad but it’s only going to get you so far.

**Comment by andydotxyz** [comment]
I agree with @Jacalz that better tutorials would add more value.
We already have a clock example in this very repository.
The examples show what can be done with the toolkit, not really stepping through code and how to do it. The code does show how these are made, obviously, so if they are not good enough maybe we could improve that too instead of duplicating.
The animation code should be demonstrated in fyne_demo "Animation" tutorial, so that seems like duplication as well.

**Comment by stuartdd2** [comment]
Will have a look ate the other approaches

**Pull request closed without merging**
