### PR TITLE
WIP: re-use same backing store for board generation

### PR DESCRIPTION
**Pull request by steveoc64**
Looking for memory leaks in game of life example.

Running the game with a forced GC every paint iteration brings the memory usage under control, so I changed around the board backing store to be statically built and re-used each paint.  This at least saves malloc'ing a whole new backing store every paint, and leaving it up to the GC to clean up.

However - what im seeing is that the stack continues to grow each paint cycle. Not sure whats causing that.

There are no go-routines leaks either - stays constant at 5 with 1 game of life loaded.  (** edit - see below **)

Needs more work.

### CODE REVIEW

**Comment by steveoc64** [comment]
Adding some debugging to solitaire as well - its got the same issue, the memory allocations and frees are good, no evidence of an obvious leak there.

However, the stack continues to grow.  Every few calls to `tableRenderer.Refresh()`   (maybe 32 calls, sometimes more, sometimes less), the stack usage jumps by 32Kb, and is never released.

Something in the GL driver I reckon.

Keep this PR in WIP status till we can get to the bottom of it.

**Comment by steveoc64** [comment]
More info 

If you run half a dozen Life's and let them go - the stack usage levels off at around 1.6MB and growth slows ... then the number of goroutines starts climbing drastically.

After a few minutes, stack tops out at just under 5MB, and the runtime.NumGoroutine() hits 2000 .. and the machine locks up hard with the CPUs pegged. Ctrl-C to get out, because its not even registering clicks anymore.

**Comment by andydotxyz** [comment]
Going through PRs and found this - is it still active? 
I see there's a "memdebug" line in so I assumed it's still WiP

**Comment by andydotxyz** [comment]
Resolved upstream?

**Comment by steveoc64** [comment]
correct - this was caused by GC - which was caused by consttantly spawning a new image - which is fixed by caching the img (rewritten Life to use NewRaster() + its own cache scheme)

closed

**Pull request closed without merging**
