### PR TITLE
Upgrade Fyne to 1.3.0 and update dependencies

### PR DESCRIPTION
**Pull request by MartyMacGyver**

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks for this. Can you also update the vendor folder for these changes please? (Easiest way is “fyne vendor” as it takes care of the embedded C code in GLFW)

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Great that this is updated, but vendor got left behind.

**Comment by MartyMacGyver** [comment]
~~Working on that now - I'm curious about this in `go.mod`, as it was recently updated to [v1.6.1](https://github.com/stretchr/testify/releases):~~

~~github.com/stretchr/testify v1.5.1~~

Nevermind testify - that's updated automatically here.

Edit: But this - is this best left alone?:

    replace golang.org/x/mobile => github.com/fyne-io/mobile v0.0.0-20191204153723-f14fb9562406

**Comment by MartyMacGyver** [comment]
These are the steps I followed:

```
# Updated `fyne.io/fyne v1.3.0` in go.mod (and removed old `replace` line)
# Then...
go get -t -u ./...
go mod tidy
fyne vendor   # Built using fyne 1.3.0
```

As the main `go.mod` was stubbornly different from what I did from a clean slate today (a few extra lines of hashes), I updated that as well here.

**Comment by andydotxyz** [comment]
> Edit: But this - is this best left alone?:

That replace line is no longer needed for 1.3.0, I forgot about that :)

**Comment by andydotxyz** [comment]
It looks like the process worked, but you're right the replace should have been removed.

Probably need to re-run after taking that out in case old mobile includes were left in.

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Looks like it worked, thanks.

Sorry I didn't notice the replace directive before, that should come out.

**Comment by MartyMacGyver** [comment]
Removed the replace, re-ran everything from scratch, and updated my notes above.

(Yet again `go.sum` changed slightly - I'm not sure if that's some kind of idiosyncrasy of `go` or what. It may be related to how it processes changes to `go.mod`)

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
Great thanks

**Pull request merged**
