### PR TITLE
Add File System Viewer showcasing File Tree

### PR DESCRIPTION
**Pull request by stuartmscott**

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is failing because vendor has not been updated. I will do that just now, rebasing this on it should fix the errror

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
I just realised that this did not have an item in the intro screen. Rehabs you can update to match the new style where we don’t have specific binaries per-project any more, then we could merge with the rest of the revised UI

**Comment by Jacalz** [comment]
Could this extended widget perhaps be moved out to https://github.com/fyne-io/fyne-x? I think it would make it much more accessible to people wanting to use a file tree 🌲🙂

**Comment by andydotxyz** [comment]
> Could this extended widget perhaps be moved out to https://github.com/fyne-io/fyne-x?

That’s a pretty good idea :) perhaps here a good example would be a file manager window that combines a few features?

**Comment by Jacalz** [comment]
That sounds good to me :+1:

**Comment by stuartmscott** [comment]
Sounds good!

**Pull request closed without merging**
